name: Print Secrets

on:
    workflow_dispatch:
      inputs:
        environment:
          type: choice
          description: 'Which environment you would want to run?'
          required: true
          default: 'migdevToqa'
          options:
            - migdevToqa
            - migqaToprod

jobs:
  print-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print secrets
        run: |
          environment="${{ github.event.inputs.environment }}"
          access_key_name="${{ vars.SOURCE_AWS_ACCESS_KEY_ID }}"
          access_key_secret_name="${{ vars.SOURCE_AWS_SECRET_ACCESS_KEY }}"
          echo "Access Key: $access_key_name"
          echo "Access Key Secret: $access_key_secret_name"
