on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Which environment you would want to run?'
        required: true
        default: 'migdevToqa'
        options:
          - migdevToqa
          - migqaToprod


          
jobs:
  print-secrets:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Check if initiator is authorized
        run: |
          authorized=false
          for initiator in "${{ vars.LIST_INITIATORS }}"; do
            echo "$initiator"
            if [[ "${{ github.actor }}" == "$initiator" ]]; then
              authorized=true
              break
            fi
          done

          if [[ $authorized == false ]]; then
            echo "Unauthorized initiator. Exiting workflow."
            exit 1
          fi

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print secrets
        run: |
          environment="${{ github.event.inputs.environment }}"
          access_key_name="${{ secrets.SOURCE_AWS_ACCESS_KEY_ID }}"
          access_key_secret_name="${{ secrets.SOURCE_AWS_SECRET_ACCESS_KEY }}"
          echo "Access Key: $access_key_name"
          echo "Access Key Secret: $access_key_secret_name"
          echo "hi"
